=== limingwei/liz/framework/ioc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="beans">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="bean" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attributeGroup ref="property_attribute" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attributeGroup ref="bean_attribute" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:attributeGroup name="bean_attribute">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="class" type="xs:string" use="required" />
	</xs:attributeGroup>

	<xs:attributeGroup name="property_attribute">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" />
	</xs:attributeGroup>
</xs:schema>

=== limingwei/liz/demo/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ioc.xsd">
	<beans>
		<bean name="druid" class="com.alibaba.druid.pool.DruidDataSource">
			<property name="url" value="${db.url}" />
			<property name="username" value="${db.username}" />
			<property name="password" value="${db.password}" />
		</bean>
		<bean class="li.aop.Account">
			<property name="dataSource" />
		</bean>
	</beans>
</config>

=== limingwei/liz/test/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ioc.xsd">
	<beans>
		<bean name="simple" class="li.dao.SimpleDataSource">
			<property name="url" value="${db.url}" />
			<property name="username" value="${db.username}" />
			<property name="password" value="${db.password}" />
		</bean>
		<bean class="test.Account">
			<property name="dataSource"/>
		</bean>		
	</beans>
</config>
